version: "3.8"

services:
  unigradicon:
    image: poravnava-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/usr/src/app/input
      - ./output:/usr/src/app/output
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh

  validacija:
    image: gitlab.lst.fe.uni-lj.si:5050/domenp/deformable-registration
    volumes:
      - ./output/reshaped:/input
      - ./output:/output
    stdin_open: true
    tty: true
    command: python evaluation.py -v
    user: "${UID}:${UID}"
  # validacija:
  #   image: gitlab.lst.fe.uni-lj.si:5050/domenp/deformable-registration
  #   volumes:
  #     - ./input:/usr/src/app/input
  #     - ./output:/usr/src/app/output
  #   stdin_open: true
  #   tty: true
  #   command: python evaluation.py -v
