version: "3.8"

services:
  registration:
    image: erazem1000/ams_izziv_24_stonic:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./input:/usr/src/app/input
      - ./output:/usr/src/app/output
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh

  validation:
    image: gitlab.lst.fe.uni-lj.si:5050/domenp/deformable-registration
    volumes:
      - ./output/reshaped_validation:/input
      - ./output:/output
    stdin_open: true
    tty: true
    command: python evaluation.py -v
    user: "${UID}:${UID}"
