version: "3.8"

services:
  unigradicon:
    image: testni-docker-e-3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/usr/src/app/input
      - ./output:/usr/src/app/output
    stdin_open: true
    tty: true
    entrypoint: ./entrypoint.sh
